[general]
live_config_reload = true
working_directory = "Workspace"
import = ["~/.config/alacritty-local/alacritty.local.toml"]

# Start flavours
# Base16 OneDark 256 - alacritty color config
# Lalit Magant (http://github.com/tilal6991)

[[colors.indexed_colors]]
color = "0xd19a66"
index = 16

[[colors.indexed_colors]]
color = "0xbe5046"
index = 17

[[colors.indexed_colors]]
color = "0x353b45"
index = 18

[[colors.indexed_colors]]
color = "0x3e4451"
index = 19

[[colors.indexed_colors]]
color = "0x565c64"
index = 20

[[colors.indexed_colors]]
color = "0xb6bdca"
index = 21

[colors.bright]
black   = "0x545862"
red     = "0xe06c75"
green   = "0x98c379"
yellow  = "0xe5c07b"
blue    = "0x61afef"
magenta = "0xc678dd"
cyan    = "0x56b6c2"
white   = "0xc8ccd4"

[colors.cursor]
cursor  = "0xabb2bf"
text    = "0x282c34"

[colors.normal]
black   = "0x282c34"
red     = "0xe06c75"
green   = "0x98c379"
yellow  = "0xe5c07b"
blue    = "0x61afef"
magenta = "0xc678dd"
cyan    = "0x56b6c2"
white   = "0xabb2bf"

[colors.primary]
background = "0x282c34"
foreground = "0xabb2bf"
# End flavours

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 550
vi_mode_style = { blinking = "On" }
unfocused_hollow = true
thickness = 2

[cursor.style]
blinking = "Never"
shape = "Beam"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"
TERMINAL = "alacritty"

[keyboard]
bindings = [
   { key = "Return", mods = "Command|Shift", action = "SpawnNewInstance" }
]

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_title = true
opacity = 1.0
title = "Alacritty"

[window.padding]
x = 0
y = 0
