# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# Environment variables for NVIDIA and proper scaling
env = GDK_SCALE,1
# env = XCURSOR_SIZE,16
env = QT_QPA_PLATFORM,wayland
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# MONITOR CONFIGURATION
# Syntax: monitor=name, resolution@hz, position, scale

# Right Monitor (Primary)
# Set to 0x0 to make it the starting point of your workspace
monitor=HDMI-A-1, 3840x2160@120, 0x0, 1.5

# Left Monitor (Secondary)
# Positioned at -2560x0 (3840 / 1.5 = 2560) to place it to the left of primary
monitor=DP-1, 3840x2160@120, -2560x0, 1.5
# monitor=DP-1, 1920x1080@120, -1920x0, 1

# Workspace Binding (Optional: Fixes workspaces to specific screens)
workspace=1, monitor:HDMI-A-1, default:true
workspace=2, monitor:DP-1
