# Font configuration
font:
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: Iosevka Nerd Font Mono
  size: 14.0
  draw_bold_text_with_bright_colors: true

shell:
  program: /bin/zsh
#   args:
#   - --login

# Startup directory
#
# Directory the shell is started in. If this is unset, or `None`, the working
# directory of the parent process will be used.
working_directory: Workspace

window:
  decorations: full

startup_mode: SimpleFullscreen
