font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: Iosevka Nerd Font Mono
  size: 11.0
  draw_bold_text_with_bright_colors: true


shell:
  program: /bin/zsh
  args:
    - --login
