[tools]
ruby = "3.4.2"
lua = "5.4.7"
node = "23.10"
python = "3.13.2"
uv = "latest"

[hooks]
# Enabling corepack will install the `pnpm` package manager specified in your
# package.json alternatively, you can also install `pnpm` with mise
postinstall = "npx corepack enable"

[settings]
always_keep_download = false
always_keep_install = false
auto_install = true
env_file = ".env"
http_timeout = "30s"
jobs = 8
plugin_autoupdate_last_check_duration = "1 week"
verbose = false
status = { missing_tools = "always", show_env = false, show_tools = false }
idiomatic_version_file_enable_tools = ["ruby", "lua", "node", "python"]
